config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/user/preferences' => 'devise/registrations#edit', as: 'user_preferences'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :albums
  resources :artists
  resources :songs do
    resources :comments, only: [:create, :update, :destroy]
  end
  get '/user/:user_id/songs', to: 'songs#index_by_user'
  get '/search', to: 'search#show', as: 'search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "songs#index"

  # Public JSON API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      #resources :albums
      #resources :artists
      resources :songs# do
      #resources :comments, only: [:create, :update, :destroy]
      #end
      get '/user/:user_id/songs', to: 'songs#index_by_user'
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  validates_presence_of :title
  has_many :songs, dependent: :destroy
  has_and_belongs_to_many :artists, dependent: :destroy
  has_one_attached :album_art
  accepts_nested_attributes_for :artists

  include PgSearch
  pg_search_scope :kinda_spelled_like,
                  :against => :title,
                  :using => :trigram
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :year, :art_url)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper

  def album_art_or_placeholder_for_album(album, classes)
    url = album.album_art.attached? ? polymorphic_url(album.album_art.attachment) : 'icons/avatar.svg'
    image_tag(url, class: classes, id: 'albumArtBox', alt: 'Album Art')
  end

end

app/views/albums/_album.html.erb
<section class="user-summary-division grid-container">
  <div class="grid-col centered-flex-container">
    <%= image_tag 'icons/avatar.svg', class: 'album-art-big margin-lr-20',
                  alt: 'Album Art' %>
  </div>
  <div class="grid-col">
    <h1 class="user-name"><%= album.title %></h1>
  </div>
</section>

app/views/albums/_card.html.erb
<div class="song-list-card">
  <div class="flex-container">
    <div>
      <%= album_art_or_placeholder_for_album card, 'album-art-list' %>
    </div>
    <div>
      <p><%= link_to card.title, url_for(card) %></p>
      <p class="sub-label">
        <% if card.artists.count > 1 %>
          <% card.artists[...-1].each do |artist| %>
            <%= link_to artist.name, url_for(artist) %> •
          <% end %>
        <% end %>
        <%= link_to card.artists.last.name, url_for(card.artists.last) %>
      </p>
    </div>
  </div>
</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :art_url, style: "display: block" %>
    <%= form.text_field :art_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/_songs.html.erb
<section class="user-song-list">
  <% if album.songs.count > 0 %>
    <%= render partial: 'songs/card', collection: album.songs %>
  <% end %>
</section>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<div class="body-flex">
  <%= render 'layouts/sidebar' %>
  <div class="root-container">
    <%= render 'layouts/navbar' %>

    <main>
      <h2 class="accent padding-20">My Albums</h2>
      <div class="margin-top-20">
        <%= render partial: 'card', collection: @albums %>
      </div>
    </main>

  </div>
</div>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<div class="body-flex">
  <%= render 'layouts/sidebar' %>
  <div class="root-container">
    <%= render 'layouts/navbar' %>

    <main>
      <div class="margin-top-20">
        <%= render @album %>
        <%= render partial: 'songs', locals: {album: @album} %>
      </div>
    </main>

  </div>
</div>