config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/user/preferences' => 'devise/registrations#edit', as: 'user_preferences'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :albums
  resources :artists
  resources :songs do
    resources :comments, only: [:create, :update, :destroy]
  end
  get '/user/:user_id/songs', to: 'songs#index_by_user'
  get '/search', to: 'search#show', as: 'search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "songs#index"

  # Public JSON API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      #resources :albums
      #resources :artists
      resources :songs# do
      #resources :comments, only: [:create, :update, :destroy]
      #end
      get '/user/:user_id/songs', to: 'songs#index_by_user'
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav>
  <%= image_tag 'icons/menu.svg', alt: 'Menu', class: 'menu-toggle', onclick: 'window.toggleMenu()' %>
  <div class="search-box">
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag 'query', nil, placeholder: 'Search...', class: 'search-box' %>
    <% end %>
  </div>
  <div class="profile-photo">
    <a href="<%= user_preferences_url %>">
      <div class="flex-container">
        <%= image_tag current_user.profile_pic_thumbnail, referrerpolicy: 'no-referrer' %>
        <p><%= current_user.name %></p>
      </div>
    </a>
  </div>
</nav>
<!--<?php if (isset($_SESSION['identifier'])) {
    require_once $_SERVER['DOCUMENT_ROOT'] . '/utils/queries.php';
    global $top_level;
    $notifications = User::check_notifications($_SESSION['id'], false);
    if ($notifications) {
        foreach ($notifications as $n) { ?>
<div class="notification-bar notification-<?= str_replace('_', '-', $n['type']) ?>">
  <p><strong>⚠ <?= $n['content'] ?></strong> •
    <?= date('d. m. Y, H:i', strtotime($n['date_time'])) ?>
    <button onclick="fetch('<?= $top_level ?>/utils/dismissNotification.php?id=<?= $n['id_notification'] ?>').then(() => location.reload())">
      Dismiss
    </button>
  </p>
</div>
<?php }
    }
}-->

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <%= link_to image_tag('logo.svg', alt: 'Logo') + 'RubyTunes', root_url, class: 'logo' %>
  <nav>
    <p>Menu</p>
    <ul>
      <li><%= link_to image_tag('icons/home.svg') + 'My Music', songs_url %></li>
      <li><%= link_to image_tag('icons/upload.svg') + 'Upload', new_song_url %></li>
      <%# ToDo: fix the following %>
      <li><%= link_to image_tag('icons/search.svg') + 'Search', search_url + '?query=' %></li>
    </ul>
    <p>Library</p>
    <ul>
      <li><%= link_to image_tag('icons/album.svg') + 'Albums', albums_url %></li>
      <li><%= link_to image_tag('icons/artist.svg') + 'Artists', artists_path %></li>
    </ul>
    <%# if current_user.admin? %>
<!--    <p>Administration</p>-->
<!--    <ul>-->
<!--      <li><%#= link_to image_tag('icons/stats') + 'Stats', 'FIXME' %></li>-->
<!--      <li><%#= link_to image_tag('icons/music') + 'Manage Songs', songs_url %></li>-->
<!--      <li><%#= link_to image_tag('icons/cohort') + 'Manage Users', 'FIXME' %></li>-->
<!--    </ul>-->
    <%# end %>
    <p>Account</p>
    <ul>
      <li><%= link_to image_tag('icons/music.svg') + 'Posted Songs', "/user/#{current_user.id}/songs" %></li>
      <li><%= link_to image_tag('icons/settings.svg') + 'Preferences', user_preferences_url %></li>
      <li><%= link_to image_tag('icons/logout.svg') + 'Log Out', destroy_user_session_path, data: {turbo_method: :delete} %></li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RubyTunes<%= ' • ' + document_title if defined?(document_title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>